# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('eno', models.IntegerField()),
                ('esal', models.IntegerField()),
                ('ecity', models.CharField(max_length=20)),
            ],
        ),
    ]
